FROM python:3.9-slim

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    python3-tk \
    portaudio19-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*  

RUN pip install --upgrade pip
COPY requirements.txt /root/
WORKDIR /root/
RUN pip install -r requirements.txt

# Codon
RUN /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
# ctranslate2
RUN pip install ctranslate2 OpenNMT-py sentencepiece

ENTRYPOINT ["python", "src/WhisperGradioApp_CPU.py"]
# ENTRYPOINT コマンド パラメータ1 パラメータ2
