FROM python:3.9-slim

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    python3-tk \
    portaudio19-dev \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*  

RUN pip install --upgrade pip
COPY requirements.txt /root/
WORKDIR /root/
RUN pip install -r requirements.txt

# ctranslate2
RUN pip install ctranslate2 OpenNMT-py sentencepiece
# transformers
RUN pip install transformers
# # Model変換
# RUN ct2-transformers-converter --model openai/whisper-large-v2 --output_dir whisper-large-v2-ct2 \
#     --copy_files tokenizer.json --quantization float16

ENTRYPOINT ["python", "src/WhisperGradioApp_CPU.py"]