# FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
# FROM python:3.9-slim

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*  

RUN pip freeze > requirements_conda.txt

# RUN . /root/.bashrc && \
#     conda update -n base -c defaults conda && \
#     conda create -n py39_env python==3.9 && \
#     conda init bashrc  && \
#     conda activate py39_env && \
#     conda install -c rdkit -c conda-forge rdkit --override-channels
RUN conda update conda
RUN conda update -n base -c defaults conda
RUN . /root/.bashrc && \
    conda init bash && \
    conda create -n py39_env python=3.9 anaconda && \
    conda activate py39_env

# CMD pip install --upgrade pip
# COPY requirements.txt /root/
# WORKDIR /root/
# CMD pip install -r requirements.txt

# # ctranslate2
# CMD pip install ctranslate2 OpenNMT-py sentencepiece
# # # transformers
# CMD pip install transformers

# ENTRYPOINT ["python", "src/WhisperGradioApp_GPU.py"]