# GPU
version: "3.9"
services:
  whisper_gpu:
    build:
      context: .
      dockerfile: ./dockerfile_GPU
    container_name: "whisper-gpu"
    # expose:
    #   - "8070"
    working_dir: "/root/"
    tty: true
    # ports:
    #   - "8070:8070"
    volumes:
      - ./src:/root/src/
    # command: sh -c 'exec $SHELL -l && conda activate py39_env && pip install --upgrade pip && pip install -r requirements_conda.txt && pip install -r requirements.txt &&ip install ctranslate2 OpenNMT-py sentencepiece && pip install transformers'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
# CPU
# version: "3"
# services:
#   whisper_cpu:
#     build:
#       context: .
#       dockerfile: ./dockerfile_CPU
#     container_name: "whisper-cpu"
#     expose:
#       - "8070"
#     working_dir: "/root/"
#     tty: true
#     ports:
#       - "8070:8070"
#     volumes:
#       - ./src:/root/src/
#     # command: sh -c 'pip install --upgrade pip && pip install -r requirements.txt'
